### ISSUE TITLE
[Question] Declaration files usage in typescript project

### ISSUE THREAD

**Issue by martinschutz78** [d3fc/d3fc#1700]
Hi,

I am really struggling to make d3fc works in my project since v15.2.1 and addition of d.ts.

In my project when I use "import fc from 'd3fc'", I have chartCartesian symbol available but the typescript compiler tells me that it is not a function.

Am I doing something wrong here ? Is there a working example of the lib using the new d.ts with typescript ?

Thank you.

**Comment by chrisprice** [comment]
So far we only have the typescript definitions for chart so I would only expect to see chartCartesian. The [simple-chart](https://github.com/d3fc/d3fc/blob/master/examples/simple-chart/index.js) example is giving me the completions I would expect to see. However, I can reproduce your problem by adding d3fc as a dependency to a hello world project.

I've created a PR which I think addresses the problem.

**Comment by chrisprice** [comment]
This should now be fixed. @martinschutz78 please could you confirm?

**Comment by chrisprice** [comment]
Example: https://codesandbox.io/s/practical-elbakyan-d1xpz?file=/src/index.ts

**Comment by martinschutz78** [comment]
Hi @chrisprice,

The fix works perfectly. 

Thank you very much ! 👍
